library(grid)

## the values are proportional to the entire width of the x axis
positionvector=c(seq(0.09, 0.85, length.out=11), 0.9, .945)
names(positionvector)=c('DHH', 'DTA', 'DTC', 'DTH', 'DTM', 'DTT', 'DTX', 'RLC', 'RLG', 'RLX', 'RIL', 'RIT', 'RST')


## this makes an axis with sup, order, and class written out

grobs <- grobTree(
  gp = gpar(fontsize = 12, fontface = "bold"), 
  textGrob(label='Superfamily:', name='Superfamily:',
           x=0.01, y=unit(2.2, "lines"),
           hjust=0, vjust=0),
  textGrob(label = "DHH", name = "DHH",
           x = positionvector['DHH'], y = unit(2.2, "lines"), 
           hjust = 0, vjust = 0, gp = gpar(col =dd.col['DHH'])),
  textGrob(label = "DTA", name = "DTA",
           x = positionvector['DTA'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTA'])),
  textGrob(label = "DTC", name = "DTC",
           x = positionvector['DTC'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTC'])),
  textGrob(label = "DTH", name = "DTH",
           x = positionvector['DTH'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTH'])),
  textGrob(label = "DTM", name = "DTM",
           x = positionvector['DTM'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTC'])),  
  textGrob(label = "DTT", name = "DTT",
           x = positionvector['DTT'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTT'])),  
  textGrob(label = "DTX", name = "DTX",
           x = positionvector['DTX'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTX'])),  
  textGrob(label = "RLC", name = "RLC",
           x = positionvector['RLC'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLC'])),
  textGrob(label = "RLG", name = "RLG",
           x = positionvector['RLG'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLG'])),  
  textGrob(label = "RLX", name = "RLX",
           x = positionvector['RLX'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLX'])),
  textGrob(label = "RIL", name = "RIL",
           x = positionvector['RIL'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RIL'])),  
  textGrob(label = "RIT", name = "RIT",
           x = positionvector['RIT'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RIT'])),  
  textGrob(label = "RST", name = "RST",
           x = positionvector['RST'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RST'])) ,
  textGrob(label="Class:", name='Class:',
           x=0.01, y=unit(1.2, 'lines'),
           hjust=0, vjust=0),
  textGrob(label="----Helitron----", name="---Helitron---",
           x=positionvector['DHH']-0.02, y=unit(1.2, "lines"),
           hjust=0, vjust=0, gp=gpar(col=dd.col['DHH'])),
  textGrob(label="------------------------------------Terminal Inverted Repeat------------------------------------", name="Terminal Inverted Repeat",
           x=(positionvector['DTH'] + positionvector['DTM'])/2 - 0.21, y=unit(1.2, 'lines'),
           hjust=0, vjust=0, gp=gpar(col='cadetblue3')),
  textGrob(label='--------------Long Terminal Repeat--------------', name='Long Terminal Repeat',
           x=positionvector['RLC']-0.02, y=unit(1.2, 'lines'),
           hjust=0, vjust=0, gp=gpar(col='blueviolet')),
  textGrob(label='----Interspersed Nuclear Element----', name='Interspersed Nuclear Element',
           x=positionvector['RIL']-0.02, y=unit(1.2, 'lines'),
           hjust=0, vjust=0, gp=gpar(col='darkorange3')),
  textGrob(label="Order:", name='Order:',
           x=0.01, y=unit(0.2, 'lines'),
           hjust=0, vjust=0),
  textGrob(label='-----------------------------------------------DNA Transposon-----------------------------------------------', name='DNA Transposon',
           x=positionvector['DHH']-0.02, y=unit(0.2, 'lines'),
           hjust=0, vjust=0, gp=gpar(col='cadetblue4')),
  textGrob(label='-----------------------------------Retrotransposon-----------------------------------', name='Retrotransposon',
           x=positionvector['RLC']-0.02, y=unit(0.2, 'lines'),
           hjust=0, vjust=0, gp=gpar(col='darkorchid4'))
)


## this ONLY plots superfamily along the x axis
grobs.supOnly <- grobTree(
  gp = gpar(fontsize = 12, fontface = "bold"), 
  textGrob(label='Superfamily:', name='Superfamily:',
           x=0.01, y=unit(2.2, "lines"),
           hjust=0, vjust=0),
  textGrob(label = "DHH", name = "DHH",
           x = positionvector['DHH'], y = unit(2.2, "lines"), 
           hjust = 0, vjust = 0, gp = gpar(col =dd.col['DHH'])),
  textGrob(label = "DTA", name = "DTA",
           x = positionvector['DTA'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTA'])),
  textGrob(label = "DTC", name = "DTC",
           x = positionvector['DTC'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTC'])),
  textGrob(label = "DTH", name = "DTH",
           x = positionvector['DTH'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTH'])),
  textGrob(label = "DTM", name = "DTM",
           x = positionvector['DTM'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTC'])),  
  textGrob(label = "DTT", name = "DTT",
           x = positionvector['DTT'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTT'])),  
  textGrob(label = "DTX", name = "DTX",
           x = positionvector['DTX'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTX'])),  
  textGrob(label = "RLC", name = "RLC",
           x = positionvector['RLC'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLC'])),
  textGrob(label = "RLG", name = "RLG",
           x = positionvector['RLG'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLG'])),  
  textGrob(label = "RLX", name = "RLX",
           x = positionvector['RLX'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLX'])),
  textGrob(label = "RIL", name = "RIL",
           x = positionvector['RIL'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RIL'])),  
  textGrob(label = "RIT", name = "RIT",
           x = positionvector['RIT'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RIT'])),  
  textGrob(label = "RST", name = "RST",
           x = positionvector['RST'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RST'])) 
)



### reset for figure 5, where we have two lines worth of y axis labels 
## the values are proportional to the entire width of the x axis
positionvector=c(seq(0.135, 0.852, length.out=11), 0.901, .938)
names(positionvector)=c('DHH', 'DTA', 'DTC', 'DTH', 'DTM', 'DTT', 'DTX', 'RLC', 'RLG', 'RLX', 'RIL', 'RIT', 'RST')

## this ONLY plots superfamily along the x axis
grobs.supOnlyFig5 <- grobTree(
  gp = gpar(fontsize = 12, fontface = "bold"), 
  textGrob(label='Superfamily:', name='Superfamily:',
           x=0.01, y=unit(2.2, "lines"),
           hjust=0, vjust=0),
  textGrob(label = "DHH", name = "DHH",
           x = positionvector['DHH'], y = unit(2.2, "lines"), 
           hjust = 0, vjust = 0, gp = gpar(col =dd.col['DHH'])),
  textGrob(label = "DTA", name = "DTA",
           x = positionvector['DTA'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTA'])),
  textGrob(label = "DTC", name = "DTC",
           x = positionvector['DTC'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTC'])),
  textGrob(label = "DTH", name = "DTH",
           x = positionvector['DTH'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTH'])),
  textGrob(label = "DTM", name = "DTM",
           x = positionvector['DTM'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTC'])),  
  textGrob(label = "DTT", name = "DTT",
           x = positionvector['DTT'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTT'])),  
  textGrob(label = "DTX", name = "DTX",
           x = positionvector['DTX'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTX'])),  
  textGrob(label = "RLC", name = "RLC",
           x = positionvector['RLC'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLC'])),
  textGrob(label = "RLG", name = "RLG",
           x = positionvector['RLG'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLG'])),  
  textGrob(label = "RLX", name = "RLX",
           x = positionvector['RLX'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLX'])),
  textGrob(label = "RIL", name = "RIL",
           x = positionvector['RIL'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RIL'])),  
  textGrob(label = "RIT", name = "RIT",
           x = positionvector['RIT'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RIT'])),  
  textGrob(label = "RST", name = "RST",
           x = positionvector['RST'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RST'])) 
)

## and fig 7 where we just want the middle plot to be annotated
### reset for figure 5, where we have two lines worth of y axis labels 
## the values are proportional to the entire width of the x axis
positionvector=c(seq(0.37, 0.64, length.out=11), 0.655, .675)
names(positionvector)=c('DHH', 'DTA', 'DTC', 'DTH', 'DTM', 'DTT', 'DTX', 'RLC', 'RLG', 'RLX', 'RIL', 'RIT', 'RST')

## this ONLY plots superfamily along the x axis
grobs.supOnlyFig7 <- grobTree(
  gp = gpar(fontsize = 12, fontface = "bold"), 
#  textGrob(label='Superfamily:', name='Superfamily:',
#           x=0.01, y=unit(2.2, "lines"),
#           hjust=0, vjust=0),
  textGrob(label = "DHH", name = "DHH",
           x = positionvector['DHH'], y = unit(2.2, "lines"), 
           hjust = 0, vjust = 0, gp = gpar(col =dd.col['DHH'])),
  textGrob(label = "DTA", name = "DTA",
           x = positionvector['DTA'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTA'])),
  textGrob(label = "DTC", name = "DTC",
           x = positionvector['DTC'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTC'])),
  textGrob(label = "DTH", name = "DTH",
           x = positionvector['DTH'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTH'])),
  textGrob(label = "DTM", name = "DTM",
           x = positionvector['DTM'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTC'])),  
  textGrob(label = "DTT", name = "DTT",
           x = positionvector['DTT'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTT'])),  
  textGrob(label = "DTX", name = "DTX",
           x = positionvector['DTX'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTX'])),  
  textGrob(label = "RLC", name = "RLC",
           x = positionvector['RLC'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLC'])),
  textGrob(label = "RLG", name = "RLG",
           x = positionvector['RLG'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLG'])),  
  textGrob(label = "RLX", name = "RLX",
           x = positionvector['RLX'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLX'])),
  textGrob(label = "RIL", name = "RIL",
           x = positionvector['RIL'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RIL'])),  
  textGrob(label = "RIT", name = "RIT",
           x = positionvector['RIT'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RIT'])),  
  textGrob(label = "RST", name = "RST",
           x = positionvector['RST'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RST'])) 
)





### update for new version of fig7
positionvector=c(seq(0.37, 0.64, length.out=11), 0.655, .675)-0.175
names(positionvector)=c('DHH', 'DTA', 'DTC', 'DTH', 'DTM', 'DTT', 'DTX', 'RLC', 'RLG', 'RLX', 'RIL', 'RIT', 'RST')

## this ONLY plots superfamily along the x axis
grobs.supOnlyFig7revision <- grobTree(
  gp = gpar(fontsize = 12, fontface = "bold"), 
#  textGrob(label='Superfamily:', name='Superfamily:',
#           x=0.01, y=unit(2.2, "lines"),
#           hjust=0, vjust=0),
  textGrob(label = "DHH", name = "DHH",
           x = positionvector['DHH'], y = unit(2.2, "lines"), 
           hjust = 0, vjust = 0, gp = gpar(col =dd.col['DHH'])),
  textGrob(label = "DTA", name = "DTA",
           x = positionvector['DTA'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTA'])),
  textGrob(label = "DTC", name = "DTC",
           x = positionvector['DTC'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTC'])),
  textGrob(label = "DTH", name = "DTH",
           x = positionvector['DTH'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTH'])),
  textGrob(label = "DTM", name = "DTM",
           x = positionvector['DTM'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTC'])),  
  textGrob(label = "DTT", name = "DTT",
           x = positionvector['DTT'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTT'])),  
  textGrob(label = "DTX", name = "DTX",
           x = positionvector['DTX'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['DTX'])),  
  textGrob(label = "RLC", name = "RLC",
           x = positionvector['RLC'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLC'])),
  textGrob(label = "RLG", name = "RLG",
           x = positionvector['RLG'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLG'])),  
  textGrob(label = "RLX", name = "RLX",
           x = positionvector['RLX'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RLX'])),
  textGrob(label = "RIL", name = "RIL",
           x = positionvector['RIL'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RIL'])),  
  textGrob(label = "RIT", name = "RIT",
           x = positionvector['RIT'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RIT'])),  
  textGrob(label = "RST", name = "RST",
           x = positionvector['RST'], y = unit(2.2, "lines"),
           hjust = 0, vjust = 0, gp = gpar(col = dd.col['RST'])) 
)
